# Build settings
name: EsmerilProgramming
description: Just for Fun

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:       '???'
author:    'EsmerilProgramming'
permalink: /blog/:year/:month/:day/:title

baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
collections:
  projects:
    output: true;
    permalink: /project/:path/
  programmers:
    output: true;
    permalink: /programmers/:path/

